.cargo_test_template: &cargo_test
  cache:
    paths:
      - cargo/
      - target/
  stage: test
  script:
    - du -hs target cargo
    - rustc --version && cargo --version
    - cargo test --verbose --jobs 1

stable:cargo:
  image: rustdocker/rust:stable
  <<: *cargo_test

beta:cargo:
  image: rustdocker/rust:beta
  <<: *cargo_test

nightly:cargo:
  image: rustdocker/rust:nightly
  <<: *cargo_test

pages:
  image: rustdocker/rust:stable
  stage: deploy
  only:
    - master
  script:
    - cargo doc
    - rm -rf public
    - mkdir public
    - cp target/doc/* public -r
  artifacts:
    paths:
    - public

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  GIT_DEPTH: "1"
